### ISSUE TITLE
Server is busy?

### ISSUE THREAD

**Issue by WesselDeZeeuw** [chathika/NL4Py#7]
Dear all.

I'm trying to set up my own project using nl4py extenstion. However, I can't get it to work. 
I am using python 2.7.15+ and JDK 1.8.0_211. I have followed the instructions and installed all the required packages. When I try to run your examples in this repository I keep on getting errors. 
I have opened the "Demo NL4Py.ipynb" file. However as soon as I try to load the model I get the following error:

```
y4JJavaError                             Traceback (most recent call last)
<ipython-input-15-626756e05d79> in <module>()
      8 for i in range(0,concurrent_runs):
      9     n = nl4py.netlogoWorkspaceFactory.newNetLogoHeadlessWorkspace()
---> 10     n.openModel(model_name)
     11     n.setParamsRandom()
     12 i = 0

c:\python27\lib\site-packages\nl4py\NetLogoHeadlessWorkspace.pyc in openModel(self, path)
     50         try:
     51             self.__path = path
---> 52             self.__bridge.openModel(self.__session,self.__path)
     53         except Py4JNetworkError as e:
     54             raise NL4PyControllerServerException("Looks like the server is unreachable! Maybe the socket is busy? Trying running nl4py.stopServer() and trying again.")#, None, sys.exc_info()[2])

c:\python27\lib\site-packages\py4j\java_gateway.pyc in __call__(self, *args)
   1284         answer = self.gateway_client.send_command(command)
   1285         return_value = get_return_value(
-> 1286             answer, self.gateway_client, self.target_id, self.name)
   1287 
   1288         for temp_arg in temp_args:

c:\python27\lib\site-packages\py4j\protocol.pyc in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling t.openModel.
: java.lang.NoSuchMethodError: org.nlogo.headless.HeadlessWorkspace.open(Ljava/lang/String;)V
	at nl4py.server.HeadlessWorkspaceController.openModel(HeadlessWorkspaceController.java:133)
	at nl4py.server.NetLogoControllerServer.openModel(NetLogoControllerServer.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Unknown Source)
```
I have tried to add the nl4py.serverStop() however this makes no difference. Also I have tried to change the path to the model, this also makes no difference. Could you help me resolve this issue?

Many thanks!
Wessel

**Comment by mrchaos** [comment]
use NetLogo6.0.2 version
Latest NetLogo version not supported yet

**Comment by deamonpog** [comment]
Yes
This was due to the previous incompatibility with NetLogo 6.1. NetLogo 6.1 compatibility was introduced since NL4Py v0.5.2. Please upgrade to the latest version (v0.5.11 at the moment) with
 `pip install --upgrade nl4py`
